/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDealershipArgs } from "./CreateDealershipArgs";
import { UpdateDealershipArgs } from "./UpdateDealershipArgs";
import { DeleteDealershipArgs } from "./DeleteDealershipArgs";
import { DealershipFindManyArgs } from "./DealershipFindManyArgs";
import { DealershipFindUniqueArgs } from "./DealershipFindUniqueArgs";
import { Dealership } from "./Dealership";
import { DealershipService } from "../dealership.service";

@graphql.Resolver(() => Dealership)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DealershipResolverBase {
  constructor(
    protected readonly service: DealershipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "read",
    possession: "any",
  })
  async _dealershipsMeta(
    @graphql.Args() args: DealershipFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Dealership])
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "read",
    possession: "any",
  })
  async dealerships(
    @graphql.Args() args: DealershipFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Dealership[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Dealership",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Dealership, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "read",
    possession: "own",
  })
  async dealership(
    @graphql.Args() args: DealershipFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Dealership | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Dealership",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Dealership)
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "create",
    possession: "any",
  })
  async createDealership(
    @graphql.Args() args: CreateDealershipArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Dealership> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Dealership",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Dealership"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Dealership)
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "update",
    possession: "any",
  })
  async updateDealership(
    @graphql.Args() args: UpdateDealershipArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Dealership | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Dealership",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Dealership"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Dealership)
  @nestAccessControl.UseRoles({
    resource: "Dealership",
    action: "delete",
    possession: "any",
  })
  async deleteDealership(
    @graphql.Args() args: DeleteDealershipArgs
  ): Promise<Dealership | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
