/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DeliveryBayCreateNestedManyWithoutDealershipsInput } from "./DeliveryBayCreateNestedManyWithoutDealershipsInput";
import { Type } from "class-transformer";
import { ExperiencePackageCreateNestedManyWithoutDealershipsInput } from "./ExperiencePackageCreateNestedManyWithoutDealershipsInput";
@InputType()
class DealershipCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryBayCreateNestedManyWithoutDealershipsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryBayCreateNestedManyWithoutDealershipsInput)
  @IsOptional()
  @Field(() => DeliveryBayCreateNestedManyWithoutDealershipsInput, {
    nullable: true,
  })
  deliveryBays?: DeliveryBayCreateNestedManyWithoutDealershipsInput;

  @ApiProperty({
    required: false,
    type: () => ExperiencePackageCreateNestedManyWithoutDealershipsInput,
  })
  @ValidateNested()
  @Type(() => ExperiencePackageCreateNestedManyWithoutDealershipsInput)
  @IsOptional()
  @Field(() => ExperiencePackageCreateNestedManyWithoutDealershipsInput, {
    nullable: true,
  })
  experiencePackages?: ExperiencePackageCreateNestedManyWithoutDealershipsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}
export { DealershipCreateInput };
