/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDeliveryBayArgs } from "./CreateDeliveryBayArgs";
import { UpdateDeliveryBayArgs } from "./UpdateDeliveryBayArgs";
import { DeleteDeliveryBayArgs } from "./DeleteDeliveryBayArgs";
import { DeliveryBayFindManyArgs } from "./DeliveryBayFindManyArgs";
import { DeliveryBayFindUniqueArgs } from "./DeliveryBayFindUniqueArgs";
import { DeliveryBay } from "./DeliveryBay";
import { BlockerFindManyArgs } from "../../blocker/base/BlockerFindManyArgs";
import { Blocker } from "../../blocker/base/Blocker";
import { Dealership } from "../../dealership/base/Dealership";
import { DeliveryBayService } from "../deliveryBay.service";

@graphql.Resolver(() => DeliveryBay)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DeliveryBayResolverBase {
  constructor(
    protected readonly service: DeliveryBayService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "read",
    possession: "any",
  })
  async _deliveryBaysMeta(
    @graphql.Args() args: DeliveryBayFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DeliveryBay])
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "read",
    possession: "any",
  })
  async deliveryBays(
    @graphql.Args() args: DeliveryBayFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeliveryBay[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DeliveryBay",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DeliveryBay, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "read",
    possession: "own",
  })
  async deliveryBay(
    @graphql.Args() args: DeliveryBayFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeliveryBay | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DeliveryBay",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DeliveryBay)
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "create",
    possession: "any",
  })
  async createDeliveryBay(
    @graphql.Args() args: CreateDeliveryBayArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeliveryBay> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DeliveryBay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DeliveryBay"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        dealership: {
          connect: args.data.dealership,
        },
      },
    });
  }

  @graphql.Mutation(() => DeliveryBay)
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "update",
    possession: "any",
  })
  async updateDeliveryBay(
    @graphql.Args() args: UpdateDeliveryBayArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeliveryBay | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DeliveryBay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DeliveryBay"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          dealership: {
            connect: args.data.dealership,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DeliveryBay)
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "delete",
    possession: "any",
  })
  async deleteDeliveryBay(
    @graphql.Args() args: DeleteDeliveryBayArgs
  ): Promise<DeliveryBay | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Blocker])
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "read",
    possession: "any",
  })
  async bayBlocker(
    @graphql.Parent() parent: DeliveryBay,
    @graphql.Args() args: BlockerFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Blocker[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Blocker",
    });
    const results = await this.service.findBayBlocker(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Dealership, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeliveryBay",
    action: "read",
    possession: "any",
  })
  async dealership(
    @graphql.Parent() parent: DeliveryBay,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Dealership | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Dealership",
    });
    const result = await this.service.getDealership(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
