/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumExperiencePackageActive } from "./EnumExperiencePackageActive";

import {
  IsEnum,
  IsOptional,
  IsDate,
  ValidateNested,
  IsBoolean,
  IsString,
  IsJSON,
  IsNumber,
} from "class-validator";

import { EnumExperiencePackageChargeable } from "./EnumExperiencePackageChargeable";
import { Type } from "class-transformer";
import { Dealership } from "../../dealership/base/Dealership";
import { GraphQLJSONObject } from "graphql-type-json";
import { JsonValue } from "type-fest";
@ObjectType()
class ExperiencePackage {
  @ApiProperty({
    required: false,
    enum: EnumExperiencePackageActive,
  })
  @IsEnum(EnumExperiencePackageActive)
  @IsOptional()
  @Field(() => EnumExperiencePackageActive, {
    nullable: true,
  })
  active?: "Active" | "Inactive" | null;

  @ApiProperty({
    required: false,
    enum: EnumExperiencePackageChargeable,
  })
  @IsEnum(EnumExperiencePackageChargeable)
  @IsOptional()
  @Field(() => EnumExperiencePackageChargeable, {
    nullable: true,
  })
  chargeable?: "Yes" | "No" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Dealership],
  })
  @ValidateNested()
  @Type(() => Dealership)
  @IsOptional()
  dealership?: Array<Dealership>;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  duration!: boolean | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  imageGallery!: JsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  keyImage!: JsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { ExperiencePackage };
